In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]


In [4]:
np.array(my_list)


array([1, 2, 3])

In [5]:
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [6]:
np.random.rand(2)


array([0.25863098, 0.9843496 ])

In [7]:
np.random.randint(1, 100)


15

In [8]:
ranarr = np.random.randint(0, 50, 10)


In [9]:
ranarr

array([40, 34, 30, 14,  0, 36, 40, 30, 45, 37])

In [10]:
# Return max index.
ranarr.argmax()

8

In [11]:
# return index of min number
ranarr.argmin()


4

In [12]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [13]:
# total_rolls_over_two = # This should be a single integer
bool_arr = dice_rolls > 2

In [14]:
# Access the part of the array and then count them.
total_rolls_over_two = dice_rolls[bool_arr].shape[0]

In [15]:
total_rolls_over_two

19

In [18]:
transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [19]:
transactions.sum()

2720