In [3]:
import numpy as np
import pandas as pd

In [4]:
my_list = [1, 2, 3]


In [5]:
np.array(my_list)


array([1, 2, 3])

In [6]:
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [7]:
np.random.rand(2)


array([0.62420011, 0.54520683])

In [8]:
np.random.randint(1, 100)


24

In [9]:
ranarr = np.random.randint(0, 50, 10)


In [10]:
ranarr

array([19,  2, 17, 38, 11, 22, 21, 14, 23,  9])

In [11]:
# Return max index.
ranarr.argmax()

3

In [12]:
# return index of min number
ranarr.argmin()


1

In [13]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [14]:
# total_rolls_over_two = # This should be a single integer
bool_arr = dice_rolls > 2

In [15]:
# Access the part of the array and then count them.
total_rolls_over_two = dice_rolls[bool_arr].shape[0]

In [16]:
total_rolls_over_two

19

In [17]:
transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [18]:
transactions.sum()

2720

In [19]:
# Imaginary Sales Data for 1st and 2nd Quarters for Global Company
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [20]:
sales_Q1 = pd.Series(q1)
sales_Q2 = pd.Series(q2)

In [24]:
# You can fill these with any value you want
sales_Q1.add(sales_Q2, fill_value=0)

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

In [6]:
path = 'D:\\NumPy-udemy\\03-Pandas\\tips.csv'
df = pd.read_csv(path)
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]